
DROP TABLE METER_PARAMETER_LINK;

CREATE TABLE METER_PARAMETER_LINK
(
	METER_VERSION 		NUMBER,
	PARAMETER_INDEX 	NUMBER,
	INTERNAL_ID 		VARCHAR2(120), 
	FORMATTER_CLASS_NAME VARCHAR2(120), 
	MULTIPLYING_FACTOR FLOAT, 
	MULTIPLY_1_P_INTERNAL_ID VARCHAR2(120), 
	MULTIPLY_2_P_INTERNAL_ID VARCHAR2(120), 
	DIVISION_1_P_INTERNAL_ID VARCHAR2(120), 
	DIVISION_2_P_INTERNAL_ID VARCHAR2(120), 
	RESERVED_1			VARCHAR2(120),
	RESERVED_2			VARCHAR2(120)
);



ALTER TABLE METER_PARAMETER_LINK ADD CONSTRAINT METER_PARAMETER_LINK_PK PRIMARY KEY (METER_VERSION, PARAMETER_INDEX);

COMMENT ON TABLE METER_PARAMETER_LINK  IS 'METER_PARAMETER_LINK';

INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(1, 4);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(1, 5);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(1, 6);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(1, 7);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(1, 8);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(1, 9);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(1, 10);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(1, 11);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(1, 12);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(1, 13);

INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(2, 4);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(2, 5);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(2, 6);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(2, 7);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(2, 8);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(2, 9);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(2, 10);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(2, 11);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(2, 12);
INSERT INTO METER_PARAMETER_LINK (METER_VERSION, PARAMETER_INDEX) VALUES(2, 13);

commit;


