
DROP TABLE METER_TYPE;

CREATE TABLE METER_TYPE
(
	METER_VERSION 		NUMBER,
	METER_TYPE_NAME 	VARCHAR(120),
	RESERVED_1			VARCHAR(120),
	RESERVED_2			VARCHAR(120)
);

ALTER TABLE METER_TYPE ADD CONSTRAINT METER_TYPE_PK PRIMARY KEY (METER_VERSION);

COMMENT ON TABLE METER_TYPE  IS 'METER_TYPE';

INSERT INTO METER_TYPE (METER_VERSION, METER_TYPE_NAME) VALUES (1, 'V1');
INSERT INTO METER_TYPE (METER_VERSION, METER_TYPE_NAME) VALUES (2, 'V2');
INSERT INTO METER_TYPE (METER_VERSION, METER_TYPE_NAME) VALUES (3, 'V3');
INSERT INTO METER_TYPE (METER_VERSION, METER_TYPE_NAME) VALUES (4, 'V4');
INSERT INTO METER_TYPE (METER_VERSION, METER_TYPE_NAME) VALUES (5, 'V5');
INSERT INTO METER_TYPE (METER_VERSION, METER_TYPE_NAME) VALUES (6, 'V6');
INSERT INTO METER_TYPE (METER_VERSION, METER_TYPE_NAME) VALUES (7, 'V7');

commit;