
DROP TABLE PARAMETER;

CREATE TABLE PARAMETER
(
	PARAMETER_INDEX 	NUMBER,
	PARAMETER_NAME 		VARCHAR2(120),
	PARAMETER_RYGB		VARCHAR2(120),
	PARAMETER_SYMBOL	VARCHAR2(20),
	PARAMETER_TYPE		NUMBER,
	RESERVED_1			VARCHAR2(120),
	RESERVED_2			VARCHAR2(120),
	PARAMETER_FORMAT	VARCHAR2(30)
);

ALTER TABLE PARAMETER ADD CONSTRAINT PARAMETER_PK PRIMARY KEY (PARAMETER_INDEX);

COMMENT ON TABLE PARAMETER  IS 'PARAMETER';

insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 4 ,'voltage1','0','V1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 5 ,'voltage2','1','V2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 6 ,'voltage3','2','V3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 7 ,'Tot voltage (ph-N)','3','Tot VPN');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 8 ,'voltage1-2','0','V12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 9 ,'voltage2-3','1','V23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 10 ,'voltage3-1','2','V31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 11 ,'Tot voltage (L-L)','3','Tot VLL');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 12 ,'Current1','0','I1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 13 ,'Current2','1','I2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 14 ,'Current3','2','I3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 15 ,'Total Current','3','Tot I');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 16 ,'power factor 1','0','PF1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 17 ,'power factor 2','1','PF2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 18 ,'power factor 3','2','PF3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 19 ,'Tot power factor','3','Tot PF');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 20 ,'Frequency R','0','Hz-R');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 21 ,'Frequency Y','1','Hz-Y');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 22 ,'Frequency B','2','Hz-B');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 23 ,'Total Frequency','3','Hz');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 24 ,'active power 1','0','W1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 25 ,'active power 2','1','W2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 26 ,'active power 3','2','W3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 27 ,'Total active power','3','Tot W');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 28 ,'reactive power 1','0','VAR1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 29 ,'reactive power 2','1','VAR2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 30 ,'reactive power 3','2','VAR3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 31 ,'Total reactive power','3','Tot VAR');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 32 ,'apparent power 1','0','VA1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 33 ,'apparent power 2','1','VA2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 34 ,'apparent power 3','2','VA3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 35 ,'Total apparent power','3','Tot VA');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 36 ,'Active Energy Phase1 (Import)','0','Wh1-Imp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 37 ,'Active Energy Phase2 (Import)','1','Wh2-Imp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 38 ,'Active Energy Phase3 (Import)','2','Wh3-Imp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 39 ,'Total Active Energy (Import)','3','Tot Wh-Imp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 40 ,'Active Energy Phase1 (Export)','0','Wh1-Exp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 41 ,'Active Energy Phase2 (Export)','1','Wh2-Exp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 42 ,'Active Energy Phase3 (Export)','2','Wh3-Exp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 43 ,'Total Active Energy (Export)','3','Tot Wh-Exp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 44 ,'Reactive Energy Phase1 (L)','0','VARh1-L');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 45 ,'Reactive Energy Phase2 (L)','1','VARh2-L');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 46 ,'Reactive Energy Phase3 (L)','2','VARh3-L');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 47 ,'Total Reactive Energy (L)','3','Tot VARh-L');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 48 ,'Reactive Energy Phase1 (C)','0','VARh1-C');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 49 ,'Reactive Energy Phase2 (C)','1','VARh2-C');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 50 ,'Reactive Energy Phase3 (C)','2','VARh3-C');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 51 ,'Total Reactive Energy (C)','3','Tot VARh-C');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 52 ,'Total Reactive Energy','3','Tot VARh');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 53 ,'Apparent Energy Phase1 (Import)','0','VAh1-Imp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 54 ,'Apparent Energy Phase2 (Import)','1','VAh2-Imp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 55 ,'Apparent Energy Phase3 (Import)','2','VAh3-Imp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 56 ,'Total Apparent Energy (Import)','3','Tot VAh-Imp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 57 ,'Apparent Energy Phase1 (Export)','0','VA1-Exp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 58 ,'Apparent Energy Phase2 (Export)','1','VA2-Exp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 59 ,'Apparent Energy Phase3 (Export)','2','VA3-Exp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 60 ,'Total Apparent Energy (Export)','3','Tot VAh-Exp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 61 ,'MD Active Power','3','Tot MD W');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 62 ,'MD Reactive Power','3','Tot MD VAR');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 63 ,'MD Apparent Power','3','Tot MD VA');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 64 ,'Maximum Active Power Line 1','0','Max W1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 65 ,'Maximum Active Power Line 2','1','Max W2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 66 ,'Maximum Active Power Line 3','2','Max W3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 67 ,'Maximum Reactive Power Line 1','0','Max VAR1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 68 ,'Maximum Reactive Power Line 2','1','Max VAR2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 69 ,'Maximum Reactive Power Line 3','2','Max VAR3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 70 ,'Maximum Apparent Power Line 1','0','Max VA1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 71 ,'Maximum Apparent Power Line 2','1','Max VA2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 72 ,'Maximum Apparent Power Line 3','2','Max VA3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 73 ,'Maximum Active Power','3','Max W');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 74 ,'Maximum Reactive Power','3','Max VAR');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 75 ,'Maximum Apparent Power','3','Max VA');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 76 ,'Average Active Power Line 1','0','AVG W1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 77 ,'Average Active Power Line 2','1','AVG W2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 78 ,'Average Active Power Line 3','2','AVG W3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 79 ,'Average 3 Ph Equivalent Active Power','3','AVG W');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 80 ,'Average Reactive Power Line 1','0','AVG VAR1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 81 ,'Average Reactive Power Line 2','1','AVG VAR2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 82 ,'Average Reactive Power Line 3','2','AVG VAR3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 83 ,'Average 3Ph Equivalent Reactive Power','3','AVG VAR');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 84 ,'Average Apparent Power Line 1','0','AVG VA1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 85 ,'Average Apparent Power Line 2','1','AVG VA2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 86 ,'Average Apparent Power Line 3','2','AVG VA3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 87 ,'Average 3Ph Equivalent ApparentPower','3','AVG VA');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 88 ,'Max. Average 3Ph Active Power','3','AVG Max W');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 89 ,'Line 1 normal format voltage ThdF','0','Thd V1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 90 ,'Line 2 normal format voltage ThdF','1','Thd V2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 91 ,'Line 3 normal format voltage ThdF','2','Thd V3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 92 ,'Tot normal format voltage ThdF','3','Tot Thd V');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 93 ,'Line 1 normal format current ThdF','0','Thd I1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 94 ,'Line 2 normal format current ThdF','1','Thd I2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 95 ,'Line 3 normal format current ThdF','2','Thd I3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 96 ,'AVG Normal format current ThdF','3','Tot Thd I');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 97 ,'Active Energy Counter 2','3','Wh Count- 2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 98 ,'Total Active Energy','3','Tot Wh');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 99 ,'Total Apparent Energy','3','Tot VAh');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 100 ,'Line 1 Reactive Power-TRUE','0','Qtrue-1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 101 ,'Line 2 Reactive Power-TRUE','1','Qtrue-2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 102 ,'Line 3 Reactive Power-TRUE','2','Qtrue-3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 103 ,'Historical Demand','3','Historical Demand');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 104 ,'Target Demand','3','Target Demand');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 105 ,'Forecast Demand','3','Forecast Demand');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 106 ,'Present Demand','3','Demand');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 107 ,'Total Voltage Harmonics','3','Tot VH');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 108 ,'Total Current Harmonics','3','Tot IH');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 109 ,'10 Voltage Harmonics','3','VH1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 110 ,'10 Voltage1 Harmonics','0','V1H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 111 ,'10 Voltage2 Harmonics','1','V2H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 112 ,'10 Voltage3 Harmonics','2','V3H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 113 ,'20 Voltage Harmonics','3','VH2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 114 ,'20 Voltage 1 Harmonics','0','V1H2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 115 ,'20 Voltage2 Harmonics','1','V2H2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 116 ,'20 Voltage3 Harmonics','2','V3H2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 117 ,'30 Voltage Harmonics','3','VH3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 118 ,'30 Voltage 1 Harmonics','0','V1H3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 119 ,'30 Voltage2 Harmonics','1','V2H3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 120 ,'30 Voltage3 Harmonics','2','V3H3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 121 ,'40 Voltage Harmonics','3','VH4');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 122 ,'40 Voltage 1 Harmonics','0','V1H4');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 123 ,'40 Voltage2 Harmonics','1','V2H4');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 124 ,'40 Voltage3 Harmonics','2','V3H4');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 125 ,'50 Voltage Harmonics','3','VH5');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 126 ,'50 Voltage 1 Harmonics','0','V1H5');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 127 ,'50 Voltage2 Harmonics','1','V2H5');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 128 ,'50 Voltage3 Harmonics','2','V3H5');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 129 ,'60 Voltage Harmonics','3','VH6');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 130 ,'60 Voltage1 Harmonics','0','V1H6');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 131 ,'60 Voltage2 Harmonics','1','V2H6');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 132 ,'60 Voltage3 Harmonics','2','V3H6');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 133 ,'70 Voltage Harmonics','3','VH7');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 134 ,'70 Voltage1 Harmonics','0','V1H7');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 135 ,'70 Voltage2 Harmonics','1','V2H7');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 136 ,'70 Voltage3 Harmonics','2','V3H7');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 137 ,'80 Voltage Harmonics','3','VH8');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 138 ,'80 Voltage1 Harmonics','0','V1H8');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 139 ,'80 Voltage2 Harmonics','1','V2H8');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 140 ,'80 Voltage3 Harmonics','2','V3H8');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 141 ,'90 Voltage Harmonics','3','VH9');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 142 ,'90 Voltage1 Harmonics','0','V1H9');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 143 ,'90 Voltage2 Harmonics','1','V2H9');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 144 ,'90 Voltage3 Harmonics','2','V3H9');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 145 ,'100 Voltage Harmonics','3','VH10');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 146 ,'100 Voltage1 Harmonics','0','V1H10');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 147 ,'100 Voltage2 Harmonics','1','V2H10');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 148 ,'100 Voltage3 Harmonics','2','V3H10');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 149 ,'110 Voltage Harmonics','3','VH11');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 150 ,'110 Voltage1 Harmonics','0','V1H11');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 151 ,'110 Voltage2 Harmonics','1','V2H11');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 152 ,'110 Voltage3 Harmonics','2','V3H11');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 153 ,'120 Voltage Harmonics','3','VH12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 154 ,'120 Voltage1 Harmonics','0','V1H12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 155 ,'120 Voltage2 Harmonics','1','V2H12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 156 ,'120 Voltage3 Harmonics','2','V3H12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 157 ,'130 Voltage Harmonics','3','VH13');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 158 ,'130 Voltage1 Harmonics','0','V1H13');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 159 ,'130 Voltage2 Harmonics','1','V2H13');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 160 ,'130 Voltage3 Harmonics','2','V3H13');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 161 ,'140 Voltage Harmonics','3','VH14');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 162 ,'140 Voltage1 Harmonics','0','V1H14');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 163 ,'140 Voltage2 Harmonics','1','V2H14');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 164 ,'140 Voltage3 Harmonics','2','V3H14');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 165 ,'150 Voltage Harmonics','3','VH15');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 166 ,'150 Voltage1 Harmonics','0','V1H15');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 167 ,'150 Voltage2 Harmonics','1','V2H15');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 168 ,'150 Voltage3 Harmonics','2','V3H15');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 169 ,'160 Voltage Harmonics','3','VH16');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 170 ,'160 Voltage1 Harmonics','0','V1H16');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 171 ,'160 Voltage2 Harmonics','1','V2H16');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 172 ,'160 Voltage3 Harmonics','2','V3H16');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 173 ,'170 Voltage Harmonics','3','VH17');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 174 ,'170 Voltage1 Harmonics','0','V1H17');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 175 ,'170 Voltage2 Harmonics','1','V2H17');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 176 ,'170 Voltage3 Harmonics','2','V3H17');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 177 ,'180 Voltage Harmonics','3','VH18');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 178 ,'180 Voltage1 Harmonics','0','V1H18');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 179 ,'180 Voltage2 Harmonics','1','V2H18');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 180 ,'180 Voltage3 Harmonics','2','V3H18');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 181 ,'190 Voltage Harmonics','3','VH19');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 182 ,'190 Voltage1 Harmonics','0','V1H19');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 183 ,'190 Voltage2 Harmonics','1','V2H19');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 184 ,'190 Voltage3 Harmonics','2','V3H19');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 185 ,'200 Voltage Harmonics','3','VH20');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 186 ,'200 Voltage1 Harmonics','0','V1H20');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 187 ,'200 Voltage2 Harmonics','1','V2H20');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 188 ,'200 Voltage3 Harmonics','2','V3H20');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 189 ,'210 Voltage Harmonics','3','VH21');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 190 ,'210 Voltage1 Harmonics','0','V1H21');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 191 ,'210 Voltage2 Harmonics','1','V2H21');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 192 ,'210 Voltage3 Harmonics','2','V3H21');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 193 ,'220 Voltage Harmonics','3','VH22');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 194 ,'220 Voltage1 Harmonics','0','V1H22');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 195 ,'220 Voltage2 Harmonics','1','V2H22');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 196 ,'220 Voltage3 Harmonics','2','V3H22');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 197 ,'230 Voltage Harmonics','3','VH23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 198 ,'230 Voltage1 Harmonics','0','V1H23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 199 ,'230 Voltage2 Harmonics','1','V2H23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 200 ,'230 Voltage3 Harmonics','2','V3H23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 201 ,'240 Voltage Harmonics','3','VH24');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 202 ,'240 Voltage1 Harmonics','0','V1H24');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 203 ,'240 Voltage2 Harmonics','1','V2H24');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 204 ,'240 Voltage3 Harmonics','2','V3H24');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 205 ,'250 Voltage Harmonics','3','VH25');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 206 ,'250 Voltage1 Harmonics','0','V1H25');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 207 ,'250 Voltage2 Harmonics','1','V2H25');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 208 ,'250 Voltage3 Harmonics','2','V3H25');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 209 ,'260 Voltage Harmonics','3','VH26');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 210 ,'260 Voltage1 Harmonics','0','V1H26');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 211 ,'260 Voltage2 Harmonics','1','V2H26');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 212 ,'260 Voltage3 Harmonics','2','V3H26');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 213 ,'270 Voltage Harmonics','3','VH27');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 214 ,'270 Voltage1 Harmonics','0','V1H27');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 215 ,'270 Voltage2 Harmonics','1','V2H27');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 216 ,'270 Voltage3 Harmonics','2','V3H27');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 217 ,'280 Voltage Harmonics','3','VH28');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 218 ,'280 Voltage1 Harmonics','0','V1H28');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 219 ,'280 Voltage2 Harmonics','1','V2H28');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 220 ,'280 Voltage3 Harmonics','2','V3H28');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 221 ,'290 Voltage Harmonics','3','VH29');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 222 ,'290 Voltage1 Harmonics','0','V1H29');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 223 ,'290 Voltage2 Harmonics','1','V2H29');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 224 ,'290 Voltage3 Harmonics','2','V3H29');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 225 ,'300 Voltage Harmonics','3','VH30');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 226 ,'300 Voltage1 Harmonics','0','V1H30');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 227 ,'300 Voltage2 Harmonics','1','V2H30');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 228 ,'300 Voltage3 Harmonics','2','V3H30');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 229 ,'310 Voltage Harmonics','3','VH31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 230 ,'310 Voltage1 Harmonics','0','V1H31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 231 ,'310 Voltage2 Harmonics','1','V2H31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 232 ,'310 Voltage3 Harmonics','2','V3H31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 233 ,'10 Current Harmonics','3','IH1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 234 ,'10 Current1 Harmonics','0','I1H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 235 ,'10 Current2 Harmonics','1','I2H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 236 ,'10 Current3 Harmonics','2','I3H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 237 ,'20 Current Harmonics','3','IH2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 238 ,'20 Current1 Harmonics','0','I1H2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 239 ,'20 Current2 Harmonics','1','I2H2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 240 ,'20 Current3 Harmonics','2','I3H2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 241 ,'30 Current Harmonics','3','IH3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 242 ,'30 Current1 Harmonics','0','I1H3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 243 ,'30 Current2 Harmonics','1','I2H3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 244 ,'30 Current3 Harmonics','2','I3H3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 245 ,'40 Current Harmonics','3','IH4');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 246 ,'40 Current1 Harmonics','0','I1H4');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 247 ,'40 Current2 Harmonics','1','I2H4');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 248 ,'40 Current3 Harmonics','2','I3H4');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 249 ,'50 Current Harmonics','3','IH5');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 250 ,'50 Current1 Harmonics','0','I1H5');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 251 ,'50 Current2 Harmonics','1','I2H5');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 252 ,'50 Current3 Harmonics','2','I3H5');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 253 ,'60 Current Harmonics','3','IH6');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 254 ,'60 Current1 Harmonics','0','I1H6');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 255 ,'60 Current2 Harmonics','1','I2H6');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 256 ,'60 Current3 Harmonics','2','I3H6');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 257 ,'70 Current Harmonics','3','IH7');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 258 ,'70 Current1 Harmonics','0','I1H7');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 259 ,'70 Current2 Harmonics','1','I2H7');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 260 ,'70 Current3 Harmonics','2','I3H7');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 261 ,'80 Current Harmonics','3','IH8');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 262 ,'80 Current1 Harmonics','0','I1H8');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 263 ,'80 Current2 Harmonics','1','I2H8');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 264 ,'80 Current3 Harmonics','2','I3H8');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 265 ,'90 Current Harmonics','3','IH9');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 266 ,'90 Current1 Harmonics','0','I1H9');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 267 ,'90 Current2 Harmonics','1','I2H9');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 268 ,'90 Current3 Harmonics','2','I3H9');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 269 ,'100 Current Harmonics','3','IH10');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 270 ,'100 Current1 Harmonics','0','I1H10');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 271 ,'100 Current2 Harmonics','1','I2H10');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 272 ,'100 Current3 Harmonics','2','I3H10');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 273 ,'110 Current Harmonics','3','IH11');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 274 ,'110 Current1 Harmonics','0','I1H11');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 275 ,'110 Current2 Harmonics','1','I2H11');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 276 ,'110 Current3 Harmonics','2','I3H11');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 277 ,'120 Current Harmonics','3','IH12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 278 ,'120 Current1 Harmonics','0','I1H12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 279 ,'120 Current2 Harmonics','1','I2H12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 280 ,'120 Current3 Harmonics','2','I3H12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 281 ,'130 Current Harmonics','3','IH13');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 282 ,'130 Current1 Harmonics','0','I1H13');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 283 ,'130 Current2 Harmonics','1','I2H13');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 284 ,'130 Current3 Harmonics','2','I3H13');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 285 ,'140 Current Harmonics','3','IH14');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 286 ,'140 Current1 Harmonics','0','I1H14');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 287 ,'140 Current2 Harmonics','1','I2H14');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 288 ,'140 Current3 Harmonics','2','I3H14');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 289 ,'150 Current Harmonics','3','IH15');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 290 ,'150 Current1 Harmonics','0','I1H15');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 291 ,'150 Current2 Harmonics','1','I2H15');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 292 ,'150 Current3 Harmonics','2','I3H15');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 293 ,'160 Current Harmonics','3','IH16');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 294 ,'160 Current1 Harmonics','0','I1H16');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 295 ,'160 Current2 Harmonics','1','I2H16');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 296 ,'160 Current3 Harmonics','2','I3H16');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 297 ,'170 Current Harmonics','3','IH17');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 298 ,'170 Current1 Harmonics','0','I1H17');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 299 ,'170 Current2 Harmonics','1','I2H17');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 300 ,'170 Current3 Harmonics','2','I3H17');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 301 ,'180 Current Harmonics','3','IH18');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 302 ,'180 Current1 Harmonics','0','I1H18');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 303 ,'180 Current2 Harmonics','1','I2H18');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 304 ,'180 Current3 Harmonics','2','I3H18');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 305 ,'190 Current Harmonics','3','IH19');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 306 ,'190 Current1 Harmonics','0','I1H19');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 307 ,'190 Current2 Harmonics','1','I2H19');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 308 ,'190 Current3 Harmonics','2','I3H19');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 309 ,'200 Current Harmonics','3','IH20');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 310 ,'200 Current1 Harmonics','0','I1H20');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 311 ,'200 Current2 Harmonics','1','I2H20');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 312 ,'200 Current3 Harmonics','2','I3H20');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 313 ,'210 Current Harmonics','3','IH21');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 314 ,'210 Current1 Harmonics','0','I1H21');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 315 ,'210 Current2 Harmonics','1','I2H21');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 316 ,'210 Current3 Harmonics','2','I3H21');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 317 ,'220 Current Harmonics','3','IH22');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 318 ,'220 Current1 Harmonics','0','I1H22');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 319 ,'220 Current2 Harmonics','1','I2H22');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 320 ,'220 Current3 Harmonics','2','I3H22');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 321 ,'230 Current Harmonics','3','IH23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 322 ,'230 Current1 Harmonics','0','I1H23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 323 ,'230 Current2 Harmonics','1','I2H23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 324 ,'230 Current3 Harmonics','2','I3H23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 325 ,'240 Current Harmonics','3','IH24');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 326 ,'240 Current1 Harmonics','0','I1H24');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 327 ,'240 Current2 Harmonics','1','I2H24');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 328 ,'240 Current3 Harmonics','2','I3H24');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 329 ,'250 Current Harmonics','3','IH25');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 330 ,'250 Current1 Harmonics','0','I1H25');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 331 ,'250 Current2 Harmonics','1','I2H25');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 332 ,'250 Current3 Harmonics','2','I3H25');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 333 ,'260 Current Harmonics','3','IH26');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 334 ,'260 Current1 Harmonics','0','I1H26');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 335 ,'260 Current2 Harmonics','1','I2H26');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 336 ,'260 Current3 Harmonics','2','I3H26');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 337 ,'270 Current Harmonics','3','IH27');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 338 ,'270 Current1 Harmonics','0','I1H27');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 339 ,'270 Current2 Harmonics','1','I2H27');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 340 ,'270 Current3 Harmonics','2','I3H27');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 341 ,'280 Current Harmonics','3','IH28');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 342 ,'280 Current1 Harmonics','0','I1H28');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 343 ,'280 Current2 Harmonics','1','I2H28');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 344 ,'280 Current3 Harmonics','2','I3H28');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 345 ,'290 Current Harmonics','3','IH29');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 346 ,'290 Current1 Harmonics','0','I1H29');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 347 ,'290 Current2 Harmonics','1','I2H29');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 348 ,'290 Current3 Harmonics','2','I3H29');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 349 ,'300 Current Harmonics','3','IH30');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 350 ,'300 Current1 Harmonics','0','I1H30');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 351 ,'300 Current2 Harmonics','1','I2H30');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 352 ,'300 Current3 Harmonics','2','I3H30');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 353 ,'310 Current Harmonics','3','IH31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 354 ,'310 Current1 Harmonics','0','I1H31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 355 ,'310 Current2 Harmonics','1','I2H31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 356 ,'310 Current3 Harmonics','2','I3H31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 357 ,'RHD Voltage Phase 1','0','Rhd V1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 358 ,'RHD Voltage Phase 2','1','Rhd V2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 359 ,'RHD Voltage Phase 3','2','Rhd V3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 360 ,'RHD Current Phase 1','0','Rhd I1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 361 ,'RHD Current Phase 2','1','Rhd I2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 362 ,'RHD Current Phase 3','2','Rhd I3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 363 ,'Cos Phi 1','0','cos PHI 1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 364 ,'Cos Phi 2','1','cos PHI 2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 365 ,'Cos Phi 3','2','cos PHI 3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 366 ,'Average Voltage Phase 1','0','AVG V1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 367 ,'Average Voltage Phase 2','1','AVG V2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 368 ,'Average Voltage Phase 3','2','AVG V3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 369 ,'Average Total Phase Voltage','3','AVG Tot VPN');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 370 ,'Average Voltage L1-L2','0','AVG V12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 371 ,'Average Voltage L2-L3','1','AVG V23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 372 ,'Average Voltage L3-L1','2','AVG V31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 373 ,'Average Total Line Voltage','3','AVG Tot VPP');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 374 ,'Average Current Phase 1','0','AVG I1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 375 ,'Average Current Phase 2','1','AVG I2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 376 ,'Average Current Phase 3','2','AVG I3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 377 ,'Average Total Current','3','AVG Tot I');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 378 ,'Average Power Factor Phase 1','0','AVG PF1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 379 ,'Average Power Factor Phase 2','1','AVG PF2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 380 ,'Average Power Factor Phase 3','2','AVG PF3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 381 ,'Average Total Power Factor','3','AVG PF');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 382 ,'Average Frequency','3','AVG Hz');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 383 ,'High Voltage Phase 1','0','High V1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 384 ,'High Voltage Phase 2','1','High V2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 385 ,'High Voltage Phase 3','2','High V3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 386 ,'High Current Phase 1','0','High I1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 387 ,'High Current Phase 2','1','High I2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 388 ,'High Current Phase 3','2','High I3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 389 ,'High Active Power Import','3','High W (Imp)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 390 ,'High Active Power Export','3','High W (Exp)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 391 ,'High Reactive Power Import','3','High VAR (Imp)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 392 ,'High Reactive Power Export','3','High VAR (Exp)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 393 ,'High Total Apparent Power','3','High VA');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 394 ,'Low Voltage Phase 1','0','Low V1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 395 ,'Low Voltage Phase 2','1','Low V2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 396 ,'Low Voltage Phase 3','2','Low V3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 397 ,'Low Current Phase 1','0','Low I1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 398 ,'Low Current Phase 2','1','Low I2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 399 ,'Low Current Phase 3','2','Low I3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 400 ,'Low Active Power Import','3','Low W (Imp)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 401 ,'Low Active Power Export','3','Low W (Exp)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 402 ,'Low Reactive Power Import','3','Low VAR (Imp)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 403 ,'Low Reactive Power Export','3','Low VAR (Exp)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 404 ,'Low Total Apparent Power','3','Low VA');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 405 ,'Max Current Phase 1','0','Max I1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 406 ,'Max Current Phase 2','1','Max I2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 407 ,'Max Current Phase 3','2','Max I3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 408 ,'Demand Current Phase 1','0','Demand I1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 409 ,'Demand Current Phase 2','1','Demand I2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 410 ,'Demand Current Phase 3','2','Demand I3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 411 ,'Capacitor Overload L1-L2','0','Capacitor O/L 1-2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 412 ,'Capacitor Overload L2-L3','1','Capacitor O/L 2-3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 413 ,'Capacitor Overload L3-L1','2','Capacitor O/L 3-1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 414 ,'High System Current','3','High I');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 415 ,'High System VPN','3','High VPN');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 416 ,'High Active Power Phase 1','0','High W1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 417 ,'High Active Power Phase 2','1','High W2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 418 ,'High Active Power Phase 3','2','High W3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 419 ,'High Active Power','3','High W');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 420 ,'Low System Current','3','Low I');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 421 ,'Low System VPN','3','Low VPN');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 422 ,'Low Active Power Phase 1','0','Low W1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 423 ,'Low Active Power Phase 2','1','Low W2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 424 ,'Low Active Power Phase 3','2','Low W3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 425 ,'Low Active Power','3','Low W');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 426 ,'Demand System Apparent Power','3','Demand VA');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 427 ,'Demand System Reactive Power','3','Demand VAR');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 428 ,'Demand System Current','3','Demand I');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 429 ,'Max Demand System Current','3','MD I');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 430 ,'VAh 1','0','VAh1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 431 ,'VAh 2','1','VAh2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 432 ,'VAh 3','2','VAh3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 433 ,'Total VAh','3','Tot VAh');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 434 ,'Total Wh1','0','Tot Wh1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 435 ,'Total Wh2','1','Tot Wh2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 436 ,'Total Wh3','2','Tot Wh3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 437 ,'Tot VARh1','0','Tot VARh1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 438 ,'Tot VARh2','1','Tot VARh2');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 439 ,'Tot VARh3','2','Tot VARh3');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 440 ,'Sys Phase - Neutral Current','3','Sys An');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 441 ,'THD V12','0','THD V12');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 442 ,'THD V23','1','THD V23');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 443 ,'THD V31','2','THD V31');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 444 ,'Voltage Unbalance','2','Unbalance V');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 445 ,'Current Unbalance','2','Unbalance I');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 446 ,'Tot Exp Inductive Energy','3','Wrh Exp (I)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 447 ,'Tot Exp Capacitive Energy','3','Wrh Exp (C)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 448 ,'Tot Imp Inductive Energy','3','Wrh Imp (I)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 449 ,'Tot Imp Capacitive Energy','3','Wrh Imp (C)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 450 ,'Average Tot Imp Inductive Power','3','Avg VAR Imp (I)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 451 ,'Average Tot Imp Capacitive Power','3','Avg VAR Imp (C)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 452 ,'Average Tot Imp Active Power ','3','Avg W Imp (I)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 453 ,'Average Tot Imp Apparent Power','3','Avg W Imp (C)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 454 ,'Average Tot Exp Inductive Power','3','Avg VAR Exp (I)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 455 ,'Average Tot Exp Capacitive Power','3','Avg VAR Exp (C)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 456 ,'Average Tot Exp Active Power ','3','Avg W Exp (I)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 457 ,'Average Tot Exp Apparent Power','3','Avg W Exp (C)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 458 ,'Tot Imp Active Power MD','3','W MD Imp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 459 ,'Tot Imp Inductive Power MD','3','VAR MD Imp (I)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 460 ,'Tot Imp Capacitive Power MD','3','VAR MD Imp (C)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 461 ,'Tot Imp Apparent Power MD','3','VA MD Imp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 462 ,'Tot Exp Active Power MD','3','W MD Exp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 463 ,'Tot Exp Inductive Power MD','3','VAR MD Exp (I)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 464 ,'Tot Exp Capacitive Power MD','3','VAR MD Exp (C)');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 465 ,'Tot Exp Apparent Power MD','3','VA MD Exp');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 466 ,'Phase Voltage Mean THD-3P3W','3','THD-M-3P3W');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 467 ,'L1H2 voltage phase angle','0','VL1 H2 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 468 ,'L1H3 voltage phase angle','0','VL1 H3 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 469 ,'L1H4 voltage phase angle','0','VL1 H4 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 470 ,'L1H5 voltage phase angle','0','VL1 H5 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 471 ,'L1H6 voltage phase angle','0','VL1 H6 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 472 ,'L1H7 voltage phase angle','0','VL1 H7 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 473 ,'L1H8 voltage phase angle','0','VL1 H8 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 474 ,'L1H9 voltage phase angle','0','VL1 H9 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 475 ,'L1H10 voltage phase angle','0','VL1 H10 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 476 ,'L1H11 voltage phase angle','0','VL1 H11 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 477 ,'L1H12 voltage phase angle','0','VL1 H12 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 478 ,'L1H13 voltage phase angle','0','VL1 H13 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 479 ,'L1H14 voltage phase angle','0','VL1 H14 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 480 ,'L1H15 voltage phase angle','0','VL1 H15 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 481 ,'L1H16 voltage phase angle','0','VL1 H16 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 482 ,'L1H17 voltage phase angle','0','VL1 H17 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 483 ,'L1H18 voltage phase angle','0','VL1 H18 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 484 ,'L1H19 voltage phase angle','0','VL1 H19 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 485 ,'L1H20 voltage phase angle','0','VL1 H20 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 486 ,'L1H21 voltage phase angle','0','VL1 H21 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 487 ,'L1H22 voltage phase angle','0','VL1 H22 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 488 ,'L1H23 voltage phase angle','0','VL1 H23 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 489 ,'L1H24 voltage phase angle','0','VL1 H24 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 490 ,'L1H25 voltage phase angle','0','VL1 H25 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 491 ,'L1H26 voltage phase angle','0','VL1 H26 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 492 ,'L1H27 voltage phase angle','0','VL1 H27 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 493 ,'L1H28 voltage phase angle','0','VL1 H28 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 494 ,'L1H29 voltage phase angle','0','VL1 H29 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 495 ,'L1H30 voltage phase angle','0','VL1 H30 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 496 ,'L1H31 voltage phase angle','0','VL1 H31 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 497 ,'L1H2 current phase angle','0','IL1 H2 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 498 ,'L1H3 current phase angle','0','IL1 H3 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 499 ,'L1H4 current phase angle','0','IL1 H4 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 500 ,'L1H5 current phase angle','0','IL1 H5 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 501 ,'L1H6 current phase angle','0','IL1 H6 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 502 ,'L1H7 current phase angle','0','IL1 H7 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 503 ,'L1H8 current phase angle','0','IL1 H8 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 504 ,'L1H9 current phase angle','0','IL1 H9 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 505 ,'L1H10 current phase angle','0','IL1 H10 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 506 ,'L1H11 current phase angle','0','IL1 H11 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 507 ,'L1H12 current phase angle','0','IL1 H12 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 508 ,'L1H13 current phase angle','0','IL1 H13 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 509 ,'L1H14 current phase angle','0','IL1 H14 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 510 ,'L1H15 current phase angle','0','IL1 H15 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 511 ,'L1H16 current phase angle','0','IL1 H16 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 512 ,'L1H17 current phase angle','0','IL1 H17 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 513 ,'L1H18 current phase angle','0','IL1 H18 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 514 ,'L1H19 current phase angle','0','IL1 H19 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 515 ,'L1H20 current phase angle','0','IL1 H20 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 516 ,'L1H21 current phase angle','0','IL1 H21 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 517 ,'L1H22 current phase angle','0','IL1 H22 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 518 ,'L1H23 current phase angle','0','IL1 H23 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 519 ,'L1H24 current phase angle','0','IL1 H24 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 520 ,'L1H25 current phase angle','0','IL1 H25 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 521 ,'L1H26 current phase angle','0','IL1 H26 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 522 ,'L1H27 current phase angle','0','IL1 H27 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 523 ,'L1H28 current phase angle','0','IL1 H28 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 524 ,'L1H29 current phase angle','0','IL1 H29 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 525 ,'L1H30 current phase angle','0','IL1 H30 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 526 ,'L1H31 current phase angle','0','IL1 H31 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 527 ,'L2H2 voltage phase angle','1','VL2 H2 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 528 ,'L2H3 voltage phase angle','1','VL2 H3 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 529 ,'L2H4 voltage phase angle','1','VL2 H4 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 530 ,'L2H5 voltage phase angle','1','VL2 H5 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 531 ,'L2H6 voltage phase angle','1','VL2 H6 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 532 ,'L2H7 voltage phase angle','1','VL2 H7 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 533 ,'L2H8 voltage phase angle','1','VL2 H8 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 534 ,'L2H9 voltage phase angle','1','VL2 H9 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 535 ,'L2H10 voltage phase angle','1','VL2 H10 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 536 ,'L2H11 voltage phase angle','1','VL2 H11 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 537 ,'L2H12 voltage phase angle','1','VL2 H12 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 538 ,'L2H13 voltage phase angle','1','VL2 H13 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 539 ,'L2H14 voltage phase angle','1','VL2 H14 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 540 ,'L2H15 voltage phase angle','1','VL2 H15 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 541 ,'L2H16 voltage phase angle','1','VL2 H16 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 542 ,'L2H17 voltage phase angle','1','VL2 H17 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 543 ,'L2H18 voltage phase angle','1','VL2 H18 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 544 ,'L2H19 voltage phase angle','1','VL2 H19 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 545 ,'L2H20 voltage phase angle','1','VL2 H20 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 546 ,'L2H21 voltage phase angle','1','VL2 H21 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 547 ,'L2H22 voltage phase angle','1','VL2 H22 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 548 ,'L2H23 voltage phase angle','1','VL2 H23 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 549 ,'L2H24 voltage phase angle','1','VL2 H24 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 550 ,'L2H25 voltage phase angle','1','VL2 H25 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 551 ,'L2H26 voltage phase angle','1','VL2 H26 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 552 ,'L2H27 voltage phase angle','1','VL2 H27 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 553 ,'L2H28 voltage phase angle','1','VL2 H28 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 554 ,'L2H29 voltage phase angle','1','VL2 H29 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 555 ,'L2H30 voltage phase angle','1','VL2 H30 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 556 ,'L2H31 voltage phase angle','1','VL2 H31 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 557 ,'L2H2 current phase angle','1','IL2 H2 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 558 ,'L2H3 current phase angle','1','IL2 H3 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 559 ,'L2H4 current phase angle','1','IL2 H4 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 560 ,'L2H5 current phase angle','1','IL2 H5 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 561 ,'L2H6 current phase angle','1','IL2 H6 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 562 ,'L2H7 current phase angle','1','IL2 H7 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 563 ,'L2H8 current phase angle','1','IL2 H8 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 564 ,'L2H9 current phase angle','1','IL2 H9 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 565 ,'L2H10 current phase angle','1','IL2 H10 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 566 ,'L2H11 current phase angle','1','IL2 H11 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 567 ,'L2H12 current phase angle','1','IL2 H12 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 568 ,'L2H13 current phase angle','1','IL2 H13 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 569 ,'L2H14 current phase angle','1','IL2 H14 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 570 ,'L2H15 current phase angle','1','IL2 H15 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 571 ,'L2H16 current phase angle','1','IL2 H16 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 572 ,'L2H17 current phase angle','1','IL2 H17 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 573 ,'L2H18 current phase angle','1','IL2 H18 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 574 ,'L2H19 current phase angle','1','IL2 H19 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 575 ,'L2H20 current phase angle','1','IL2 H20 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 576 ,'L2H21 current phase angle','1','IL2 H21 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 577 ,'L2H22 current phase angle','1','IL2 H22 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 578 ,'L2H23 current phase angle','1','IL2 H23 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 579 ,'L2H24 current phase angle','1','IL2 H24 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 580 ,'L2H25 current phase angle','1','IL2 H25 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 581 ,'L2H26 current phase angle','1','IL2 H26 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 582 ,'L2H27 current phase angle','1','IL2 H27 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 583 ,'L2H28 current phase angle','1','IL2 H28 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 584 ,'L2H29 current phase angle','1','IL2 H29 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 585 ,'L2H30 current phase angle','1','IL2 H30 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 586 ,'L2H31 current phase angle','1','IL2 H31 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 587 ,'L3H2 voltage phase angle','2','VL3 H2 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 588 ,'L3H3 voltage phase angle','2','VL3 H3 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 589 ,'L3H4 voltage phase angle','2','VL3 H4 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 590 ,'L3H5 voltage phase angle','2','VL3 H5 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 591 ,'L3H6 voltage phase angle','2','VL3 H6 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 592 ,'L3H7 voltage phase angle','2','VL3 H7 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 593 ,'L3H8 voltage phase angle','2','VL3 H8 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 594 ,'L3H9 voltage phase angle','2','VL3 H9 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 595 ,'L3H10 voltage phase angle','2','VL3 H10 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 596 ,'L3H11 voltage phase angle','2','VL3 H11 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 597 ,'L3H12 voltage phase angle','2','VL3 H12 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 598 ,'L3H13 voltage phase angle','2','VL3 H13 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 599 ,'L3H14 voltage phase angle','2','VL3 H14 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 600 ,'L3H15 voltage phase angle','2','VL3 H15 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 601 ,'L3H16 voltage phase angle','2','VL3 H16 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 602 ,'L3H17 voltage phase angle','2','VL3 H17 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 603 ,'L3H18 voltage phase angle','2','VL3 H18 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 604 ,'L3H19 voltage phase angle','2','VL3 H19 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 605 ,'L3H20 voltage phase angle','2','VL3 H20 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 606 ,'L3H21 voltage phase angle','2','VL3 H21 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 607 ,'L3H22 voltage phase angle','2','VL3 H22 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 608 ,'L3H23 voltage phase angle','2','VL3 H23 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 609 ,'L3H24 voltage phase angle','2','VL3 H24 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 610 ,'L3H25 voltage phase angle','2','VL3 H25 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 611 ,'L3H26 voltage phase angle','2','VL3 H26 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 612 ,'L3H27 voltage phase angle','2','VL3 H27 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 613 ,'L3H28 voltage phase angle','2','VL3 H28 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 614 ,'L3H29 voltage phase angle','2','VL3 H29 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 615 ,'L3H30 voltage phase angle','2','VL3 H30 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 616 ,'L3H31 voltage phase angle','2','VL3 H31 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 617 ,'L3H2 current phase angle','2','IL3 H2 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 618 ,'L3H3 current phase angle','2','IL3 H3 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 619 ,'L3H4 current phase angle','2','IL3 H4 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 620 ,'L3H5 current phase angle','2','IL3 H5 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 621 ,'L3H6 current phase angle','2','IL3 H6 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 622 ,'L3H7 current phase angle','2','IL3 H7 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 623 ,'L3H8 current phase angle','2','IL3 H8 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 624 ,'L3H9 current phase angle','2','IL3 H9 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 625 ,'L3H10 current phase angle','2','IL3 H10 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 626 ,'L3H11 current phase angle','2','IL3 H11 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 627 ,'L3H12 current phase angle','2','IL3 H12 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 628 ,'L3H13 current phase angle','2','IL3 H13 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 629 ,'L3H14 current phase angle','2','IL3 H14 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 630 ,'L3H15 current phase angle','2','IL3 H15 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 631 ,'L3H16 current phase angle','2','IL3 H16 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 632 ,'L3H17 current phase angle','2','IL3 H17 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 633 ,'L3H18 current phase angle','2','IL3 H18 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 634 ,'L3H19 current phase angle','2','IL3 H19 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 635 ,'L3H20 current phase angle','2','IL3 H20 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 636 ,'L3H21 current phase angle','2','IL3 H21 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 637 ,'L3H22 current phase angle','2','IL3 H22 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 638 ,'L3H23 current phase angle','2','IL3 H23 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 639 ,'L3H24 current phase angle','2','IL3 H24 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 640 ,'L3H25 current phase angle','2','IL3 H25 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 641 ,'L3H26 current phase angle','2','IL3 H26 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 642 ,'L3H27 current phase angle','2','IL3 H27 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 643 ,'L3H28 current phase angle','2','IL3 H28 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 644 ,'L3H29 current phase angle','2','IL3 H29 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 645 ,'L3H30 current phase angle','2','IL3 H30 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 646 ,'L3H31 current phase angle','2','IL3 H31 Angle');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 647 ,'UL1 fundamental voltage (H1)','0','UL1 H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 648 ,'UL2 fundamental voltage (H1)','1','UL2 H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 649 ,'UL3 fundamental voltage (H1)','2','UL3 H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 650 ,'IL1 fundamental current (H1)','0','IL1 H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 651 ,'IL2 fundamental current (H1)','1','IL2 H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 652 ,'IL3 fundamental current (H1)','2','IL3 H1');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 653 ,'CT Primary','0','CT P');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 654 ,'CT Secondary','0','CT S');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 655 ,'PT Primary','0','PT P');
insert into  PARAMETER  (parameter_index,parameter_name,parameter_RYGB,parameter_symbol ) values ( 656 ,'PT Secondary','0','PT S');


