
DROP TABLE ROLE;

CREATE TABLE ROLE
(
	ROLE_INDEX 		NUMBER,
	ROLE_NAME		VARCHAR(10) NOT NULL,
	CREATE_DATE		TIMESTAMP,
	MODIFIED_DATE	TIMESTAMP
);

ALTER TABLE ROLE ADD CONSTRAINT ROLE_PK PRIMARY KEY (ROLE_INDEX);

COMMENT ON TABLE ROLE  IS 'ROLE';

INSERT INTO ROLE (ROLE_INDEX, ROLE_NAME) VALUES(1, 'Administrator');
INSERT INTO ROLE (ROLE_INDEX, ROLE_NAME) VALUES(2, 'Employee');

