
DROP TABLE DATA_TABLE;

CREATE TABLE DATA_TABLE
(
		METER_INDEX			NUMBER,
		PARAMETER_INDEX 	NUMBER,
		VAL					NUMBER,
		DATA_TYPE			NUMBER,
		DATE_TIME_STAMP		TIMESTAMP,
		CREATE_DATE			TIMESTAMP
);

ALTER TABLE DATA_TABLE ADD CONSTRAINT DATA_TABLE_PK PRIMARY KEY (METER_INDEX, PARAMETER_INDEX, DATE_TIME_STAMP);

COMMENT ON TABLE DATA_TABLE  IS 'DATA_TABLE';

