
DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE
(
	EMP_ID 					VARCHAR(120) NOT NULL,
	EMP_FIRST_NAME			VARCHAR(120) NOT NULL,
	EMP_LAST_NAME			VARCHAR(120) NOT NULL,
	EMP_LOCALE				VARCHAR(120),
	EMP_ADDRESS_LINE_1		VARCHAR(120),
	EMP_ADDRESS_LINE_2		VARCHAR(120),
	EMP_ADDRESS_CITY		VARCHAR(120),
	EMP_ADDRESS_COUNTRY		VARCHAR(120),
	EMP_ADDRESS_PINCODE		NUMBER,
	EMP_ADDRESS_CONTACTNO	VARCHAR(120),
	ROLE_INDEX 				NUMBER,
	COMPANY_ID				NUMBER,
	CREATE_DATE				TIMESTAMP,
	MODIFIED_DATE			TIMESTAMP,
	ENCRYPTED_PWD			VARCHAR(120) NOT NULL,
	EMP_STATUS				NUMBER NOT NULL,
	PASSWORD_RESET_PIN		VARCHAR(120) NOT NULL
);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMP_ID);

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_FK1 FOREIGN KEY (ROLE_INDEX) REFERENCES ROLE (ROLE_INDEX);

COMMENT ON TABLE EMPLOYEE  IS 'EMPLOYEE';

INSERT INTO EMPLOYEE (EMP_ID, EMP_FIRST_NAME, EMP_LAST_NAME, ENCRYPTED_PWD, EMP_STATUS, PASSWORD_RESET_PIN , COMPANY_ID) 
VALUES ('alkesh', 'alkesh', 'chalke', 'dWBvaWds', '1', '0', 1);

INSERT INTO EMPLOYEE (EMP_ID, EMP_FIRST_NAME, EMP_LAST_NAME, ENCRYPTED_PWD, EMP_STATUS, PASSWORD_RESET_PIN, COMPANY_ID) 
VALUES ('test', 'Test', 'User', 'mGlnmA==', '1', '0', 1);




