
DROP TABLE ALARM_TABLE;

CREATE TABLE ALARM_TABLE
(
		STORE_ID 				VARCHAR(10),
		METER_INDEX				NUMBER,
		PARAMETER_INDEX 		NUMBER,
		VAL						NUMBER,
		SETED_HIGH_VALUE		NUMBER,
		SETED_LOW_VALUE			NUMBER,
		SETED_HIGH_HIGH_VALUE	NUMBER,
		SETED_LOW_LOW_VALUE		NUMBER,
		DATA_TYPE				NUMBER,
		DATE_TIME_STAMP			TIMESTAMP
);

ALTER TABLE ALARM_TABLE ADD CONSTRAINT ALARM_TABLE_PK PRIMARY KEY (FEEDER_NAME);


COMMENT ON TABLE ALARM_TABLE  IS 'ALARM_TABLE';


INSERT INTO ALARM_TABLE
(STORE_ID, METER_INDEX, PARAMETER_INDEX, VAL, SETED_HIGH_VALUE, SETED_LOW_VALUE, SETED_HIGH_HIGH_VALUE, SETED_LOW_LOW_VALUE, DATA_TYPE, DATE_TIME_STAMP)
VALUES(11111, 1, 1, 1, 1, 1, 1, 1, 1, DATE('2015-01-01'));

