
DROP TABLE EMPLOYEE_STORE_LINK;

CREATE TABLE EMPLOYEE_STORE_LINK
(
	EMP_ID 		NUMBER,
	STORE_ID 	NUMBER
);

ALTER TABLE EMPLOYEE_STORE_LINK ADD CONSTRAINT EMPLOYEE_STORE_LINK_PK PRIMARY KEY (EMP_ID, STORE_ID);

COMMENT ON TABLE EMPLOYEE_STORE_LINK  IS 'EMPLOYEE_STORE_LINK';

INSERT INTO EMPLOYEE_STORE_LINK (EMP_ID, STORE_ID) VALUES(1, 11111);
INSERT INTO EMPLOYEE_STORE_LINK (EMP_ID, STORE_ID) VALUES(2, 11111);

