
DROP TABLE FEEDER_PROFILE;

CREATE TABLE FEEDER_PROFILE
(
		METER_VERSION	NUMBER, 
		METER_INDEX		NUMBER NOT NULL,
		FEEDER_NAME		VARCHAR(120),
		METER_ID		NUMBER,
		COMP_ID			NUMBER,
		UNIT_ID			NUMBER
);

ALTER TABLE FEEDER_PROFILE ADD CONSTRAINT FEEDER_PROFILE_PK PRIMARY KEY (METER_INDEX);

ALTER TABLE FEEDER_PROFILE ADD CONSTRAINT FEEDER_PROFILE_FK1 FOREIGN KEY (COMP_ID) REFERENCES STORE (COMPANY_ID);
ALTER TABLE FEEDER_PROFILE ADD CONSTRAINT FEEDER_PROFILE_FK2 FOREIGN KEY (UNIT_ID) REFERENCES UNIT (UNIT_ID);

COMMENT ON TABLE FEEDER_PROFILE  IS 'FEEDER_PROFILE';


INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(1, 1,'Feeder 1', 1, 1, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(2, 2,'Feeder 2', 1, 2, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(1, 3,'Feeder 3', 1, 1, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(2, 4,'Feeder 4', 1, 2, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(1, 5,'Feeder 5', 1, 1, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(2, 6,'Feeder 6', 1, 2, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(1, 7,'Feeder 7', 1, 1, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(2, 8,'Feeder 8', 1, 2, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(1, 9,'Feeder 9', 1, 1, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(2, 10,'Feeder 10', 1, 2, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(1, 11,'Feeder 11', 1, 1, 1);

INSERT INTO FEEDER_PROFILE
(METER_VERSION, METER_INDEX, FEEDER_NAME, METER_ID, COMP_ID, UNIT_ID)
VALUES(2, 12,'Feeder 12', 1, 2, 1);

